language: php

php:
  - 5.4

before_script:
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update --force-yes
    - sudo apt-get install -qq --force-yes libxss1 google-chrome-stable
    - bin/travis_build_before

script:
    - phpunit -c app
    - php -d memory_limit=2048M bin/behat @MyProjectWebsiteBundle --verbose

notifications:
  email:
    - travis@kunstmaan.be
