language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sudo pear config-set auto_discover 1
    - sudo pear install -f pear.phpqatools.org/phpqatools pear.netpirates.net/phpDox
    - phpenv rehash
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev --no-interaction install

script: build/build_script

notifications:
  email:
    - travis@kunstmaan.be
