language: php

cache:
  apt: true
  bundler: true
  directories:
    - vendor

php:
  - 5.4
  - 5.5

before_script:
    - bin/travis_build_before

script:
    - phpunit -c app
    - php -d memory_limit=2048M bin/behat @MyProjectWebsiteBundle --verbose

notifications:
  email:
    - travis@kunstmaan.be
